window.allQuestions = [
  { "q": "Hvað heitir 1.stig kenninga Piagets um þroskun hugsunar/vitsmuna", "a": "Skynhreyfistig", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað heitir 2.stig kenninga Piagets um þroskun hugsunar/vitsmuna", "a": "Foraðgerðastig", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað heitir 3.stig kenninga Piagets um þroskun hugsunar/vitsmuna", "a": "Hlutbundnar Aðgerðir", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað heitir 4.stig kenninga Piagets um þroskun hugsunar/vitsmuna", "a": "Formlegar Aðgerðir", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hver er talin vera fyrsta þroskasálfræðibókin", "a": "Hugsun barnsins", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hver skrifaði fyrstu þroskasálfræðibókina", "a": "Wihlem Preyers", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað nefnist greindarþátturinn sem Spearman kom með árið 1904", "a": "G-þátturinn", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað áttu fyrstu greindarprófin að mæla", "a": "Meðfædda hæfileika", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað kallast það þegar börn tileinka sér gildismat foreldra sinna og taka upp atferli þeirra", "a": "Samsömun", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Ericson taldi að um átta stig væru að ræða í kenningu sinni um...", "a": "Félags- og sálþroskaskeið", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hver taldi huga barns vera óskrifað blað við fæðingu", "a": "Wilhelm Preyer", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað stjórnar frumsjálfinu samkvæmt kenningum Freuds", "a": "Vellíðunarlögmálið", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað stjórnar sjálfinu samkvæmt kenningum Freuds", "a": "Veruleikalögmálið", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Hvað stjórnar yfirsjálfinu samkvæmt kenningum Freuds", "a": "Fullkomnunarlögmálið", "category": "Félags og sálfræði", "level": 2 },
  { "q": "Á hvað trúir níhílisti", "a": "ekkert", "category": "Trúfræði", "level": 2 },
  { "q": "Hver var nefndur Glaðnir", "a": "Óðinn", "category": "Trúfræði", "level": 3 },
  { "q": "Hvað dvaldi Jesús marga daga í eyðimörkinni", "a": "Fjörutíu", "category": "Trúfræði", "level": 1 },
  { "q": "Á hvaða tungumáli var Nýja Testamentið skrifað", "a": "Grísku", "category": "Trúfræði", "level": 1 },
  { "q": "Hvaða félag hafði það á stefnuskrá sinni að undirbúa komu mannkynsfræðarans eða endurkomu Krists", "a": "Stjarnan í austri", "category": "Trúfræði", "level": 3 },
  { "q": "Hvað skapaði Guð fyrst samkvæmt fyrstu setningu Biblíunnar", "a": "Himinn og jörð", "category": "Trúfræði", "level": 1 },
  { "q": "Á hvaða fjalli er talið að örkin hans Nóa hafi strandað", "a": "Ararat", "category": "Trúfræði", "level": 2 },
  { "q": "Á hvaða tungumáli var Gamla testamentið ritað", "a": "Hebresku", "category": "Trúfræði", "level": 2 },
  { "q": "Hver skírði Krist", "a": "Jóhannes skírari", "category": "Trúfræði", "level": 2 },
  { "q": "Hver sagði: \"Sá yðar, sem syndlaus er, kasti fyrstur steini á hana\"", "a": "Jesús", "category": "Trúfræði", "level": 1 },
  { "q": "Hver er helgasta borg múhameðstrúarmanna", "a": "Mekka", "category": "Trúfræði", "level": 1 },
  { "q": "Hver var upphafsmaður íslamstrúar", "a": "Múhameð", "category": "Trúfræði", "level": 2 },
  { "q": "Hvaða rómverski landstjóri yfirheyrði Krist", "a": "Pontíus Pílatus", "category": "Trúfræði", "level": 2 },
  { "q": "Hver var mestur hinna keltnesku guða", "a": "Dagdha", "category": "Trúfræði", "level": 3 },
  { "q": "Hvað mynda allar hlaðnar agnir", "a": "Rafsvið", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað heitir sá kraftur sem verkar á hlaðna ögn í einsleitu rafsviði", "a": "Rafkraftur", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað er E í formúlunni E=F/q=U/d", "a": "Rafsviðsstyrkur", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað er annað orð yfir rafstöðuorku á hleðslueiningu", "a": "Rafmætti", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað kallast segulmögnuð efni frá náttúrunnar hendi sem unnt er að segulmagna varanlega", "a": "Síseglar", "category": "Eðlisfræði", "level": 2 },
  { "q": "B er hlutfallsfasti í formúlunni B=F/Qv, hvað kallast þessi fasti", "a": "Segulflæðisþéttleiki", "category": "Eðlisfræði", "level": 3 },
  { "q": "Hvaða tæki virkar þannig að rafeindir eða jónir fara með vaxandi hraða eftir hringbraut með óbreyttum radíus", "a": "Samhraðall", "category": "Eðlisfræði", "level": 2 },
  { "q": "Í kjarnorkurannsóknarstofnun Evrópu (CERN) er LEP-hraðallinn. Fyrir hvað stendur LEP", "a": "Large Electron-Positron Collider", "category": "Eðlisfræði", "level": 3 },
  { "q": "Utan úr geimnum berast sterki geislar í átt til jarðar, hvað eru þeir kallaðir", "a": "Geimgeislar", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað kallast sá hluti geimgeisla sem stöðvast í efstu lögum lofthjúpsins", "a": "Frumgeislar", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað er straumur rafeinda og róteinda (vetniskjarna) frá sólinni kallaður", "a": "Sólvindur", "category": "Eðlisfræði", "level": 1 },
  { "q": "Hvað er reglan kölluð sem notuð er til þess að finna stefnu segulsviðs inni í spólu", "a": "Hægrihandarreglan", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað er það horn kallað sem flæðisþéttleiki jarðsegulsviðiðsins myndar við láréttan flöt", "a": "Segulhalli", "category": "Eðlisfræði", "level": 2 },
  { "q": "Á hvaða tíðni í Khz virka AM útvörp á", "a": "550 til 1700", "category": "Eðlisfræði", "level": 3 },
  { "q": "Hvaða rafsegulbylgjur eru notaðar til þess að hita mat", "a": "Örbylgjur", "category": "Eðlisfræði", "level": 1 },
  { "q": "Hvaða rafsegulgeislun eru til þess að taka mynd af innviði hluta", "a": "Röntgengeislar", "category": "Eðlisfræði", "level": 1 },
  { "q": "Hvaða rafsegulgeislun gerir fólk brúnt", "a": "Útfjólubláir geislar", "category": "Eðlisfræði", "level": 1 },
  { "q": "Hverning geislun varð Dr. Banner í \"The Incredible Hulk\" fyrir", "a": "Gammageislun", "category": "Eðlisfræði", "level": 1 },
  { "q": "Hvað er inn í róteindum og nifteindum", "a": "Kvarkar", "category": "Eðlisfræði", "level": 2 },
  { "q": "Hvað er 9/9+999", "a": "1000", "category": "Stærðfræði", "level": 1 },
  { "q": "Hvað er 23*432*41*0*20", "a": "0", "category": "Stærðfræði", "level": 1 },
  { "q": "Hvað er 100-90+5-1", "a": "14", "category": "Stærðfræði", "level": 1 },
  { "q": "Hvað er 600*4", "a": "2400", "category": "Stærðfræði", "level": 1 },
  { "q": "Hversu oft þarfta að margfalda 4 með 5 til þess að fá 60", "a": "3", "category": "Stærðfræði", "level": 1 },
  { "q": "Hvað eru margar gráður í hring", "a": "360", "category": "Stærðfræði", "level": 1 },
  { "q": "Hver er hornasumma ferhyrnings", "a": "360", "category": "Stærðfræði", "level": 1 },
  { "q": "Hver er hornasumma þrýhyrnings", "a": "180", "category": "Stærðfræði", "level": 1 },
  { "q": "Í þríhyrningi ef eitt horn er 20° og annað 60°, hvað er þriðja hornið margar gráður", "a": "100", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvar er hringurinn stór í radíum", "a": "2 pi", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvar er hálf hringurinn stór í radíum", "a": "pi", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvert er markgildi fallsins f(x)=sin(x) þegar x nálgast pi", "a": "0", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvert er markgildi fallsins f(x)=x³ þegar x nálgast 3", "a": "27", "category": "Stærðfræði", "level": 3 },
  { "q": "Hvert er markgildi fallsins f(x)=sqrt(x) þegar x nálgast 81", "a": "9", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvaða tölur að undanskildri sjálfri sér og einum ganga upp í 23", "a": "Engar", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvaða tölur að undanskildri sjálfri sér og einum ganga upp í 10", "a": "2 og 5", "category": "Stærðfræði", "level": 2 },
  { "q": "Hvert er margfeldi 111 með sjálfri sér", "a": "12321", "category": "Stærðfræði", "level": 3 },
  { "q": "Hvað er 3 í öðru veldi", "a": "9", "category": "Stærðfræði", "level": 1 },
  { "q": "Hver er kvaðratrótin af 144", "a": "12", "category": "Stærðfræði", "level": 2 },
  { "q": "Eftir hvað mörg ár frá árinu 2000 mun Hale-Bopp koma aftur inn í sólkerfið okkar", "a": "2381", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hvaða halastjarna kom svo nálægt Júpiter árið 1993 að hún brotnaði upp útaf rosalegu þyngdarafli Júpiters", "a": "Shoemaker-Levy", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hvað átti Giotto ómannaða könnunarfarið að kanna", "a": "Halastjörnu", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hvert af hinum fjóru stóru tuglunum sem hringsóla Júpiter er nálægast plánetunni", "a": "Io", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hversu margir dagar er einn dagur á tunglinu", "a": "27", "category": "Stjörnufræði", "level": 2 },
  { "q": "Á milli hvaða reikistjarna í sólkerfinu okkar er flesta loftsteinana að finna", "a": "Mars og Júpíter", "category": "Stjörnufræði", "level": 1 },
  { "q": "Hver uppgötaði Plútó árið 1930", "a": "Clyde Tombaugh", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hvaða maður upphvötaði fyrstur Neptúnus", "a": "Johann Galle", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hver upphvötaði fyrstur Úranus", "a": "William Herschel", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hvað ár var \"Sputnik\" skotið á loft", "a": "1957", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hver er talinn vera upphafsmaðurinn í því að nota útvarpssjónauka við stjörnufræðilegar athuganir", "a": "Karl Jansky", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hvaða er M31 betur þekkt sem", "a": "Andromeda", "category": "Stjörnufræði", "level": 1 },
  { "q": "Hversu margra milljarða ára gamallt er sólkerfið okkar talið vera", "a": "4,6", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hvað heitir tungl Plútó", "a": "Charon", "category": "Stjörnufræði", "level": 3 },
  { "q": "Þegar Plútó fer á milli Neptúnús og Sólarinnar, í hversu mörg ár varir það", "a": "20", "category": "Stjörnufræði", "level": 3 },
  { "q": "Hvaða reikistjarna í sólkerfinu snýst um sjálfa sig í andstæða átt miðað við jörðina", "a": "Venus", "category": "Stjörnufræði", "level": 2 },
  { "q": "Úr hvaða efni eru hringir Satúrns aðallega úr", "a": "Ís", "category": "Stjörnufræði", "level": 1 },
  { "q": "Hvert er hitastig á yfirborði Plútó í celsíusgráðum", "a": "-230", "category": "Stjörnufræði", "level": 2 },
  { "q": "Hvað heitir myndin með syngjandi kakkalökkum", "a": "Joe's Apartment", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Kevin Smith hefur leikstýrt nokkrum myndum og leikur jafnan í þeim líka. Hvað heitir persónan sem hann leikur", "a": "Silent Bob", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hvaða persónur leika Jason Mewes og Kevin Smith saman", "a": "Jay og Silent Bob", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hver lék aðalkvenhlutverkið í kvikmyndinni \"Junior\"", "a": "Emma Thompson", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Hver leikstýrði myndinni \"Peggy Sue Got Married\"", "a": "Francis Ford Coppola", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hvað heitir myndin sem byggð er á sögu rapparans Eminen", "a": "8 Mile", "category": "Kvikmyndir og sjónvarpsefni", "level": 1 },
  { "q": "Hvað heitir mynd númer tvö í röðinni um Jurassic Park", "a": "The Lost World", "category": "Kvikmyndir og sjónvarpsefni", "level": 1 },
  { "q": "Í hvaða vampírumynd lék Kiefer Sutherland einu sinni", "a": "The Lost Boys", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Lát hvernig dýrs varð til þess að Ace Ventura gerðist munkur", "a": "Þvottabjarnar", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hvað heitir seinni myndin um gæludýraspæjarann Ace Ventura", "a": "When Nature Calls", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Í hvaða mynd átti Ben Affleck að ræna spilavíti í Las Vegas", "a": "Reindeer Games", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Hvaða númer bar VW Bjallan Herbie", "a": "53", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Hvað heitir þriðja myndin í American Pie seríunni í Bandaríkjunum", "a": "American Wedding", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hvaða nafn ber myndin Evil Woman í Bandaríkjunum", "a": "Saving Silverman", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Hvaða ítalski leikari/leikstjóri kom, sá og sigraði á óskarsverðlaunahátíðinni 1998", "a": "Roberto Benigni", "category": "Kvikmyndir og sjónvarpsefni", "level": 3 },
  { "q": "Hvað hét Darth Vader áður", "a": "Anakin Skywalker", "category": "Kvikmyndir og sjónvarpsefni", "level": 1 },
  { "q": "Hvað vann Titanic til margra Óskarsverðlauna", "a": "11", "category": "Kvikmyndir og sjónvarpsefni", "level": 2 },
  { "q": "Hver samdi lagið \"Icct Hedral\"", "a": "Philip Glass", "category": "Tónlist", "level": 3 },
  { "q": "Hvaða gamla hljómsveit fór fyrst með lagið \"Video Killed The Radio Star\"", "a": "Buggles", "category": "Tónlist", "level": 3 },
  { "q": "Hvaða hljómsveit gerði lagið \"Everybody Dance Now\" frægt", "a": "C&C Music Factory", "category": "Tónlist", "level": 2 },
  { "q": "Hverjir gerðu lagið \"Puff The Magic Dragon\"", "a": "Peter Paul and Mary", "category": "Tónlist", "level": 3 },
  { "q": "Í hvaða mynd eftir Stanley Kubrick er lagið \"Overture To The Sun\"", "a": "Clockwork Orange", "category": "Tónlist", "level": 3 },
  { "q": "Hver lék á gítar í laginu \"One Man Army\" eftir Prodigy", "a": "Tom Morello", "category": "Tónlist", "level": 2 },
  { "q": "Hvað hét fyrsta lag Prodigy", "a": "What Evil Lurks", "category": "Tónlist", "level": 3 },
  { "q": "Hvaða lag ásamt \"What Evil Lurks\" var á fyrstu smáskífu Prodigy", "a": "We Gonna Rock", "category": "Tónlist", "level": 3 },
  { "q": "Hvað hét fyrsta breiðskífa Prodigy", "a": "Experience", "category": "Tónlist", "level": 2 },
  { "q": "Á hvaða plötu var lagið \"No Good (Start The Dance)\"", "a": "Music For The Jilted Generation", "category": "Tónlist", "level": 2 },
  { "q": "Hvað hét smáskífu remixið af \"Poison\" eftir Prodigy", "a": "Rat Poison", "category": "Tónlist", "level": 3 },
  { "q": "Í hvaða hljómsveit var Rob Zombie áður en hann fór út í sóló feril", "a": "White Zombie", "category": "Tónlist", "level": 2 },
  { "q": "Hver syngur með Rob Zombie í laginu \"Iron Head\"", "a": "Ozzy Osbourne", "category": "Tónlist", "level": 2 },
  { "q": "Í hvaða lagi eftir sjálfan sig notar Snow sama text og í \"Lonely Monday Mornings\"", "a": "Informer", "category": "Tónlist", "level": 3 },
  { "q": "Hvað hét hljómborðsleikarinn í Prodigy", "a": "Liam Howlett", "category": "Tónlist", "level": 2 },
  { "q": "Hvað var eina konan í Prodigy kölluð", "a": "Sharky", "category": "Tónlist", "level": 3 }
].map(q => ({ ...q, points: q.points ?? q.level ?? 1 }));
